services:
  backend:
    build: ./backend
    container_name: node-backend
    ports:
      - "3001:3001"
    restart: always

  frontend:
    build: ./frontend
    container_name: node-frontend
    ports:
      - "3005:3005"
    restart: always
    depends_on:
      - backend

